/joy_mux:
  ros__parameters:
    topics:
      steamdeck_lora:
        topic   : rove/lora/steamdeck/joy
        timeout : 0.5
        priority: 101
      xbox_lora:
        topic   : rove/lora/xbox/joy
        timeout : 0.5
        priority: 100
      steamdeck_uhard:
        topic   : rove/uhard/steamdeck/joy
        timeout : 0.5
        priority: 91
      xbox_uhard:
        topic   : rove/uhard/xbox/joy
        timeout : 0.5
        priority: 90
      others:
        topic   : rove/other/joy
        timeout : 0.5
        priority: 10

/scheme_selector:
  ros__parameters:
    button1_index: 14 # DPAD_LEFT
    button2_index: 15 # DPAD_RIGHT

/teleop_twist_joy_node:
  ros__parameters:
    axis_angular:
      pitch: -1 # not set
      roll: -1 # not set
      yaw: 0 # LS_X
    axis_linear:
      x: 1 # LS_Y
      y: -1 # not set
      z: -1 # not set
    enable_button: 5 # RB
    enable_turbo_button: 0 # not set
    require_enable_button: true
    scale_angular:
      pitch: 0.0
      roll: 0.0
      yaw: 1.5
    scale_angular_turbo:
      pitch: 0.0
      roll: 0.0
      yaw: 2.0
    scale_linear:
      x: 1.5
      y: 0.0
      z: 0.0
    scale_linear_turbo:
      x: 2.0
      y: 0.0
      z: 0.0
    # publish_stamped_twist: true

/tank_twist_node:
  ros__parameters:
    wheel_separation: 0.230
    wheel_radius: 0.11

    wheel_separation_multiplier: 10.0
    left_wheel_radius_multiplier: -0.0325
    right_wheel_radius_multiplier: 0.0325

/estop_control:
  ros__parameters:
    button1_index: 8 # SUPER (xbox/steamdeck button)  [ESTOP ON]
    button2_index: 1 # B                              [ESTOP OFF]

/enable_node:
  ros__parameters:
    button1_index: 5 # RB

/front_flippers_enable_node:
  ros__parameters:
    button1_index: 16 # LT_BTN

/rear_flippers_enable_node:
  ros__parameters:
    button1_index: 17 # RT_BTN