/twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: nav_vel
        timeout: 0.5
        priority: 10
      twist:
        topic: twist_vel
        timeout: 0.5
        priority: 20
      tank:
        topic: tank_vel
        timeout: 0.5
        priority: 21
      others:
        topic: cmd_vel
        timeout: 0.5
        priority: 1